#include <minitest.h>
#include <ranges>
#include <shared_lib.h>
#include <static_lib.h>
using namespace std;

int main(int argc, char *argv[])
{
    MINITEST_RUN_TEST(argc, argv);
    minitest::shared_lib::shared_lib_dummy_func();
    minitest::static_lib::static_lib_dummy_func();
    cout << "executable:Hello, World!" << endl;
    cout << "Test expectations. The following error messages generated by EXPECT_* macros will not cause the program "
            "to fail."
         << endl;
    EXPECT_TRUE(false);
    EXPECT_FALSE(true);
    EXPECT_THROW(throw runtime_error("runtime_error");, logic_error);
    EXPECT_THROW(throw 1.0;, int);    
    EXPECT_THROW(throw 1;, float,"`1` is an int.");
    EXPECT_THROW(throw 1.0;, int);    
    EXPECT_NO_THROW(throw runtime_error("runtime_error"));
    cout << "executable: bye!" << endl;
    return EXIT_SUCCESS;
}
