#include <Atliac/minitest.h>
#include <ranges>
#ifdef minitest_SHARED_LIB
#include <shared_lib.h>
#endif // minitest_SHARED_LIB
#include <static_lib.h>
using namespace std;

int main(int argc, char *argv[])
{
    MINITEST_RUN_TESTS(argc, argv);
#ifdef minitest_SHARED_LIB
    shared_lib::shared_lib_dummy_func();
#endif // minitest_SHARED_LIB
    static_lib::static_lib_dummy_func();
    cout << "executable:Hello, World!" << endl;
    cout << "Test expectations. The following error messages generated by EXPECT_* macros will not cause the program "
            "to fail."
         << endl;
    EXPECT_TRUE(false);
    EXPECT_FALSE(true);
    EXPECT_THROW(throw runtime_error("runtime_error");, logic_error);
    EXPECT_THROW(throw 1.0;, int);
    EXPECT_THROW(throw 1;, float, "`1` is an int.");
    EXPECT_THROW(throw 1.0;, int);
    EXPECT_NO_THROW(throw runtime_error("runtime_error"));
    cout << "executable: bye!" << endl;
    return EXIT_SUCCESS;
}
